

name: shellscript test
on: push
# branches-ignore: '**'
jobs:
    scripts:
        if: true
        runs-on: ubuntu-latest

        strategy:
          fail-fast: false
          matrix:
            script:
            # - scripts/deploy/cp/__cp_etc_sysctl.d.sh
            # - scripts/deploy/mkdir/__mkdir.sh
            # - test.sh

        steps:
          - name: chekout
            uses: actions/checkout@v4

          - name: test script
            run:  ${GITHUB_WORKSPACE}/${{ matrix.script }}


    makefile:
        if: false
        runs-on: ubuntu-latest

        steps:
          - name: chekout
            uses: actions/checkout@v4

          - name: test
            run:  setup.sh
